### ISSUE TITLE
Decide on project goals

### ISSUE THREAD

**Issue by Goblinlordx** [Free-Code-Camp-Seoul/fcc-store-2020#1]
What shall we build?

Time limit?
- Start: 2020-10-24
- End: 2020-11-28

Who?
- @Goblinlordx 
- @damienminter 
- @minkyngkm
- @drecali

**Comment by Goblinlordx** [comment]
Here are some places that have some ideas for possible projects:

https://bootcamp.ce.ucf.edu/blog/top-10-coding-projects-for-beginners/

https://medium.com/better-programming/10-great-programming-projects-to-improve-your-resume-and-learn-to-program-74b14d3e9e16

https://www.codementor.io/@npostolovski/40-side-project-ideas-for-software-engineers-g8xckyxef

https://www.makeuseof.com/tag/beginner-programming-projects/

**Comment by damienminter** [comment]
bug-english

App that users can log dodgy Korean to English language translations either by taking a photo or typing in the translation and then assign them against the company that made them (example in the below link)

https://www.pinterest.com/pin/16747829835838201/?nic_v2=1a4vTusER

Idea is that the company could be contacted about the mistake and potentially a reward could be offered. Like Bug Bounty for security floors on apps (similar to HackerOne etc). 

Basic Requirments

1. Home page showing recently bugs capture (skeleton done - Needs a lot of work)
2. Page to log a new bug (basic done - Need a lot of work)
3. Naver Api to search for the company and grab details (done, functional but needs improvement)
4. Company Page to see info and list of bugs for each company (basic done - Needs work)

Other requirements 

1. Connect to database firebase
2. Ability to log in as a user
3. Same for organization/admin (maybe)
4. Other

Git hub repo (current state)
https://github.com/damienminter/bug-english

Tech used
React (functional components) Redux (react-redux hooks) React router dom and Material UI

**Comment by Goblinlordx** [comment]
Based on discussion we will build a Online store.
